//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porucbenica
    {
        public int OsobaId { get; set; }
        public string ImePrezime { get; set; }
        public string Telefon { get; set; }
        public string Ulica { get; set; }
        public string KucniBroj { get; set; }
        public string PostanskiBroj { get; set; }
        public string Mesto { get; set; }
        public string StaPorucujete { get; set; }
        public Nullable<int> Kolicina { get; set; }
    }
}
