//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OsobaCon", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceWebShop")]
    [System.SerializableAttribute()]
    public partial class OsobaCon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImePrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KucniBrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OsobaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostanskiBrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaPorucujeteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImePrezime {
            get {
                return this.ImePrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImePrezimeField, value) != true)) {
                    this.ImePrezimeField = value;
                    this.RaisePropertyChanged("ImePrezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KucniBroj {
            get {
                return this.KucniBrojField;
            }
            set {
                if ((object.ReferenceEquals(this.KucniBrojField, value) != true)) {
                    this.KucniBrojField = value;
                    this.RaisePropertyChanged("KucniBroj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesto {
            get {
                return this.MestoField;
            }
            set {
                if ((object.ReferenceEquals(this.MestoField, value) != true)) {
                    this.MestoField = value;
                    this.RaisePropertyChanged("Mesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OsobaId {
            get {
                return this.OsobaIdField;
            }
            set {
                if ((this.OsobaIdField.Equals(value) != true)) {
                    this.OsobaIdField = value;
                    this.RaisePropertyChanged("OsobaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostanskiBroj {
            get {
                return this.PostanskiBrojField;
            }
            set {
                if ((object.ReferenceEquals(this.PostanskiBrojField, value) != true)) {
                    this.PostanskiBrojField = value;
                    this.RaisePropertyChanged("PostanskiBroj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaPorucujete {
            get {
                return this.StaPorucujeteField;
            }
            set {
                if ((object.ReferenceEquals(this.StaPorucujeteField, value) != true)) {
                    this.StaPorucujeteField = value;
                    this.RaisePropertyChanged("StaPorucujete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica {
            get {
                return this.UlicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UlicaField, value) != true)) {
                    this.UlicaField = value;
                    this.RaisePropertyChanged("Ulica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Porucbenica", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceWebShop")]
    [System.SerializableAttribute()]
    public partial class Porucbenica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImePrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KucniBrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OsobaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostanskiBrojField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaPorucujeteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImePrezime {
            get {
                return this.ImePrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImePrezimeField, value) != true)) {
                    this.ImePrezimeField = value;
                    this.RaisePropertyChanged("ImePrezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kolicina {
            get {
                return this.KolicinaField;
            }
            set {
                if ((this.KolicinaField.Equals(value) != true)) {
                    this.KolicinaField = value;
                    this.RaisePropertyChanged("Kolicina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KucniBroj {
            get {
                return this.KucniBrojField;
            }
            set {
                if ((object.ReferenceEquals(this.KucniBrojField, value) != true)) {
                    this.KucniBrojField = value;
                    this.RaisePropertyChanged("KucniBroj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesto {
            get {
                return this.MestoField;
            }
            set {
                if ((object.ReferenceEquals(this.MestoField, value) != true)) {
                    this.MestoField = value;
                    this.RaisePropertyChanged("Mesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OsobaId {
            get {
                return this.OsobaIdField;
            }
            set {
                if ((this.OsobaIdField.Equals(value) != true)) {
                    this.OsobaIdField = value;
                    this.RaisePropertyChanged("OsobaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostanskiBroj {
            get {
                return this.PostanskiBrojField;
            }
            set {
                if ((object.ReferenceEquals(this.PostanskiBrojField, value) != true)) {
                    this.PostanskiBrojField = value;
                    this.RaisePropertyChanged("PostanskiBroj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaPorucujete {
            get {
                return this.StaPorucujeteField;
            }
            set {
                if ((object.ReferenceEquals(this.StaPorucujeteField, value) != true)) {
                    this.StaPorucujeteField = value;
                    this.RaisePropertyChanged("StaPorucujete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ulica {
            get {
                return this.UlicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UlicaField, value) != true)) {
                    this.UlicaField = value;
                    this.RaisePropertyChanged("Ulica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebShopService")]
    public interface IWebShopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/VratiOsobe", ReplyAction="http://tempuri.org/IWebShopService/VratiOsobeResponse")]
        WebShop.ServiceReference1.OsobaCon[] VratiOsobe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/VratiOsobe", ReplyAction="http://tempuri.org/IWebShopService/VratiOsobeResponse")]
        System.Threading.Tasks.Task<WebShop.ServiceReference1.OsobaCon[]> VratiOsobeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/PreuzmiOsobe", ReplyAction="http://tempuri.org/IWebShopService/PreuzmiOsobeResponse")]
        WebShop.ServiceReference1.OsobaCon[] PreuzmiOsobe(WebShop.ServiceReference1.Porucbenica os);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/PreuzmiOsobe", ReplyAction="http://tempuri.org/IWebShopService/PreuzmiOsobeResponse")]
        System.Threading.Tasks.Task<WebShop.ServiceReference1.OsobaCon[]> PreuzmiOsobeAsync(WebShop.ServiceReference1.Porucbenica os);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/ObrisiPorudzbinu", ReplyAction="http://tempuri.org/IWebShopService/ObrisiPorudzbinuResponse")]
        WebShop.ServiceReference1.OsobaCon[] ObrisiPorudzbinu(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebShopService/ObrisiPorudzbinu", ReplyAction="http://tempuri.org/IWebShopService/ObrisiPorudzbinuResponse")]
        System.Threading.Tasks.Task<WebShop.ServiceReference1.OsobaCon[]> ObrisiPorudzbinuAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebShopServiceChannel : WebShop.ServiceReference1.IWebShopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebShopServiceClient : System.ServiceModel.ClientBase<WebShop.ServiceReference1.IWebShopService>, WebShop.ServiceReference1.IWebShopService {
        
        public WebShopServiceClient() {
        }
        
        public WebShopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebShopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebShopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebShop.ServiceReference1.OsobaCon[] VratiOsobe() {
            return base.Channel.VratiOsobe();
        }
        
        public System.Threading.Tasks.Task<WebShop.ServiceReference1.OsobaCon[]> VratiOsobeAsync() {
            return base.Channel.VratiOsobeAsync();
        }
        
        public WebShop.ServiceReference1.OsobaCon[] PreuzmiOsobe(WebShop.ServiceReference1.Porucbenica os) {
            return base.Channel.PreuzmiOsobe(os);
        }
        
        public System.Threading.Tasks.Task<WebShop.ServiceReference1.OsobaCon[]> PreuzmiOsobeAsync(WebShop.ServiceReference1.Porucbenica os) {
            return base.Channel.PreuzmiOsobeAsync(os);
        }
        
        public WebShop.ServiceReference1.OsobaCon[] ObrisiPorudzbinu(int id) {
            return base.Channel.ObrisiPorudzbinu(id);
        }
        
        public System.Threading.Tasks.Task<WebShop.ServiceReference1.OsobaCon[]> ObrisiPorudzbinuAsync(int id) {
            return base.Channel.ObrisiPorudzbinuAsync(id);
        }
    }
}
